FROM ubuntu
MAINTAINER zhangzhentao

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:ethereum/ethereum
RUN apt-get update
RUN apt-get install -y ethereum
RUN mkdir /var/eth_data

ENTRYPOINT geth --datadir /var/eth_data --rpcapi eth,web3,personal,debug,admin --cache 1024  --port 30303 --rpc --rpcport 8545 --rpcaddr 0.0.0.0
