FROM ubuntu
MAINTAINER zhangzhentao


RUN apt-get update
RUN apt-get install -y python-pip
RUN apt-get install -y nginx
RUN apt-get install -y mongodb-clients
RUN pip install --upgrade pip
RUN pip install Flask
RUN pip install Flask-JSONRPC
RUN pip install gevent
RUN pip install gunicorn
RUN pip install txmongo
RUN pip install twisted
RUN python -m pip install pymongo
RUN pip install requests

