FROM ubuntu
MAINTAINER zhangzhentao


RUN apt-get update
RUN apt-get install -y python-pip
RUN apt-get install -y nginx
RUN pip install --upgrade pip
RUN pip install Flask
RUN pip install Flask-JSONRPC
RUN python -m pip install pymongo

