#!/bin/bash

ACTION=

usage()
{
    echo "usage:`basename $0` [-a ACTION] [-h]"
    exit 1
}

parse_args()
{
    while getopts :ha: c $@
    do
        case $c in
        a)
            ACTION=$OPTARG
            ;;
        h)
            usage
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            exit 1
            ;;
        esac
    done

    if [ "$ACTION" = "" ]; then
        usage
    fi
}

start_service()
{
    if [ -f /var/www/html/init_db.js ]; then
        mongo --host chaindb  chaindb /var/www/html/init_db.js
        mv /var/www/html/init_db.js /var/www/html/init_db.js.imported
    fi
    /etc/init.d/nginx start
    [ -d /var/www/html/logs ] || mkdir /var/www/html/logs
    cd /var/www/html
    exec gunicorn -c gunicorn.conf app:app
}

take_action()
{
    if [ "$ACTION" = "start" ]; then
        echo "Action: $ACTION"
        start_service
    elif [ "$ACTION" = "stop" ]; then
        echo "Action: $ACTION"
    elif [ "$ACTION" = "restart" ]; then
        echo "Action: $ACTION"
    else
        echo "Invalid action: $ACTION"
    fi
}

parse_args $*
take_action